# -*- org -*-

#+STARTUP: hidestars oddeven

# HINT: org-mode global cycling: S-TAB
#
# HINT: To show all content (including any drawers), regardless of org-mode
# startup visibility:
#
#     C-u C-u C-u TAB
#
# [The above assumes the default key binding of TAB to [[elisp:org-cycle][org-cycle]].]

* History of 'at' (and friends) on BSD

** Background context: USL lawsuit, plus BSD 1990-1994

   The history of at(1) within the BSD's may or may not have been influenced
   the lawsuits between Unix System Laboratories (USL) and Berkeley Software
   Design, Incorporated (BSDI) between 1992 and 1994. Marshall Kirk McKusick's
   write-up of the events, as published in 1999 by O'Reilly in the book "Open
   Sources: Voices from the Open Source Revolution" can be read online here:

       https://www.oreilly.com/openbook/opensources/book/kirkmck.html

   The main points of that as it may involve the history of the 'at' command in
   the BSD's, AFAICT, are:

   1. The timing 1992-1994 spans the time at which the Linux kernel was
      released to the Internet and had a flurry of "fleshing-out the base
      system" sort of work that could have been the motivation for one or more
      developers to seek out an at(1) command for the system (from elsewhere,
      or to write a new one from scratch).

   2. The pre-Koenig at(1) that was present before the lawsuit in the
      4.4BSD-Reno distribution from early 1990 (and presumably also in the
      later Net/2 BSD distribution (which started shipping in June 1991))
      survived to also be present in the 4.4BSD-Lite released in June 1994
      (after the lawsuit had been settled earlier that same year, in January).

      At the above URL, McKusick writes of the lawsuit settlement:
      #+BEGIN_QUOTE
          The result was that three files were removed from the 18,000 that
          made up Networking Release 2, and a number of minor changes were made
          to other files. In addition, the University agreed to add USL
          copyrights to about 70 files, although those files continued to be
          freely redistributed.
      #+END_QUOTE

      From those two pieces of information, it appears to me that at.c was one
      of those approximately 70 files to which a USL copyright was added. You
      can compare the two versions by making use of the cross-distribution
      comparison tool made available by The Unix Heritage Society (TUHS) here:

          https://www.tuhs.org/cgi-bin/utree.pl?file=4.4BSD/usr/src/usr.bin/at/at/at.c

      There's no direct URL for the comparison diff; you'll need to go to the
      above link to view the 4.4BSD-Lite version of the file, and on that web
      page use the "Compare this file to the similar file:" drop-down list to
      select the file from another BSD distribution with which to compare (and
      then hit the "Side Scroll" button). In this case, choose the entry that
      is labelled:

      :   "550: 4.3BSD-Reno/src/usr.bin/at/at/at.c"

      The copyright notice at the top of 'at.c' in the earlier (circa 1990)
      version of the file contains the following statement [line numbers added
      by the above mentioned web-based comparison tool]:

      #+BEGIN_QUOTE
      :   0001: /*
      :   0002:  * Copyright (c) 1983 Regents of the University of California.
      :   0003:  * All rights reserved.  The Berkeley software License Agreement
      :   0004:  * specifies the terms and conditions for redistribution.
      :   0005:  */
      :   0006:
      #+END_QUOTE

      The copyright notice at the top of 'at.c' in the later (circa 1994-06)
      version of the file contains the following statement [line numbers added
      by the above mentioned web-based comparison tool]:

      #+BEGIN_QUOTE
      :   0001: /*-
      :   0002:  * Copyright (c) 1983, 1993
      :   0003:  *	The Regents of the University of California.  All rights reserved.
      :   0004:  *
      :   0005:  * This module is believed to contain source code proprietary to AT&T.
      :   0006:  * Use and redistribution is subject to the Berkeley Software License
      :   0007:  * Agreement and your Software Agreement with AT&T (Western Electric).
      :   0008:  */
      :   0009:
      #+END_QUOTE

   3. Entirely separate from the USL/BSDI lawsuit stuff (and before that
      occurred), Keith Bostic had been out soliciting help from developers all
      over the Internet to write parts of the system that would make up the
      Net/2 Distribution. At the above URL, McKusick describes the events thus:

      #+BEGIN_QUOTE
          He [Bostic] solicited folks to rewrite the Unix utilities from
          scratch based solely on their published descriptions. Their only
          compensation would be to have their name listed among the Berkeley
          contributors next to the name of the utility that they rewrote. The
          contributions started slowly and were mostly for the trivial
          utilities. But as the list of completed utilities grew and Bostic
          continued to hold forth for contributions at public events such as
          Usenix, the rate of contributions continued to grow. Soon the list
          crossed one hundred utilities and within 18 months nearly all the
          important utilities and libraries had been rewritten.
      #+END_QUOTE

      Could an at(1) rewrite have been considered, and perhaps even underway,
      due to Bostic's above noted effort? (even though the existing 'at.c' from
      pre-Net/2 would survive into 4.4BSD-Lite).

   4. FreeBSD 1.0 was first released in December 1993 (6 months before the 4.4BSD-Lite)

      In the "FreeBSD Handbook", there is an introduction entitled "A Brief
      History of FreeBSD" written by Jordan K. Hubbard <jkh@FreeBSD.ORG>:

          https://docs.freebsd.org/doc/2.2.6-RELEASE/usr/share/doc/handbook/history.html

      He writes:

      #+BEGIN_QUOTE
          The first CDROM (and general net-wide) distribution was FreeBSD 1.0,
          released in December of 1993. This was based on the 4.3BSD-Lite
          ("Net/2") tape from U.C. Berkeley, with many components also
          provided by 386BSD and the Free Software Foundation. It was a fairly
          reasonable success for a first offering, and we followed it with the
          highly successful FreeBSD 1.1 release in May of 1994.
      #+END_QUOTE

      Note those dates: the first two releases of FreeBSD (1.0 and 1.1) were
      both made /before/ the 4.4BSD-Lite release was made in June 1994. That
      scenario actually created some additional work for the FreeBSD (and
      NetBSD and 386BSD) folks:

      #+BEGIN_QUOTE
          Around this time [spring of 1994], some rather unexpected storm
          clouds formed on the horizon as Novell and U.C. Berkeley settled
          their long-running lawsuit over the legal status of the Berkeley
          Net/2 tape. A condition of that settlement was U.C. Berkeley's
          concession that large parts of Net/2 were "encumbered" code and
          the property of Novell, who had in turn acquired it from AT&T
          some time previously. What Berkeley got in return was Novell's
          "blessing" that the 4.4BSD-Lite release, when it was finally
          released, would be declared unencumbered and all existing Net/2
          users would be strongly encouraged to switch. This included
          FreeBSD, and the project was given until the end of July 1994 to
          stop shipping its own Net/2 based product. Under the terms of that
          agreement, the project was allowed one last release before the
          deadline, that release being FreeBSD 1.1.5.1.

          FreeBSD then set about the arduous task of literally re-inventing
          itself from a completely new and rather incomplete set of
          4.4BSD-Lite bits. The "Lite" releases were light in part because
          Berkeley's CSRG had removed large chunks of code required for
          actually constructing a bootable running system (due to various
          legal requirements) and the fact that the Intel port of 4.4 was
          highly incomplete. It took the project until December of 1994 to
          make this transition, and in January of 1995 it released
          FreeBSD 2.0 to the net and on CDROM.
      #+END_QUOTE

      By the time of the FreeBSD "re-inventing", however, the Koenig version
      of at(1) was already part of the system.


** 2.11BSD (circa 1992) has pre-Koenig at(1) command

   The 2BSD source line dates originally from 1979, but 2.11BSD was issued
   in 1992. This at.c command /is not/ the version written by Thomas Koenig:

       https://minnie.tuhs.org/cgi-bin/utree.pl?file=2.11BSD/src/usr.bin/at/at.c

   Note that the above URL is hosted by The Unix Heritage Society (tuhs.org).

   The copyright notice at the top of the file does not mention anything about
   AT&T:

   #+BEGIN_SRC c
   /*
    * Copyright (c) 1983 Regents of the University of California.
    * All rights reserved.  The Berkeley software License Agreement
    * specifies the terms and conditions for redistribution.
    */
   #+END_SRC

   Compare that with the copyright heading of the file in 4.4BSD.


** 4.4BSD (circa 1993) also has pre-Koenig at(1), now with AT&T tainted copyright note

       https://www.tuhs.org/cgi-bin/utree.pl?file=4.4BSD/usr/src/usr.bin/at/at/at.c

   The copyright notice at the top of the file now mentions AT&T:

   #+BEGIN_SRC c
   /*-
    * Copyright (c) 1983, 1993
    *	The Regents of the University of California.  All rights reserved.
    *
    * This module is believed to contain source code proprietary to AT&T.
    * Use and redistribution is subject to the Berkeley Software License
    * Agreement and your Software Agreement with AT&T (Western Electric).
    */
   #+END_SRC

   Compare that with the copyright heading of the file in the earlier 2.11BSD.


** NetBSD (1993-12-05) has Koenig at(1) at initial commit for at.c, at.1

   This is the initial scm commit for the file:

   :   src/usr.bin/at/at.c

   in the NetBSD source tree.

       http://cvsweb.netbsd.org/bsdweb.cgi/src/usr.bin/at/at.c?rev=1.1&content-type=text/x-cvsweb-markup&only_with_tag=MAIN

   The scm commit message on the above reads:

   #+BEGING_QUOTE
   :    Revision 1.1, Sun Dec 5 11:36:38 1993 UTC (26 years, 3 months ago) by cgd
   :    Branch: MAIN
   :
   :    add at, by Thomas Koenig, ig25@rz.uni-karlsruhe.de
   #+END_QUOTE

   According to this:

       https://www.netbsd.org/people/developers.html

   The 'cgd' author of the commit is Chris Demetriou.


** FreeBSD (1994-01-04) has Koenig at(1) at initial commit for at.c

   This is the initial scm commit for the file:

   :   usr.bin/at/at.c

   in the FreeBSD source tree:

       https://github.com/freebsd/freebsd/commit/bef639521001043085233d09fd5baf914056a884#diff-eb7badfc5a22849125ad99aacd38ed05

   The scm commit message on the above reads:

   #+BEGIN_QUOTE
   :   commit bef639521001043085233d09fd5baf914056a884
   :   Author: nate <nate@FreeBSD.org>
   :   Date:   Wed Jan 5 01:09:14 1994 +0000
   :
   :       Added at/atrm/atq/batch from Linux as hacked by Chris Demetriou.
   #+END_QUOTE

   No further changes are evident in the scm history for that file in
   connection with the UCL/CSRG/BSDI lawsuit.


* History of 'at' (and friends) on GNU/Linux

** 1992-08-11: comp.os.linux thread (1 msg): "/bin/at, /usr/lib/atrun, & /etc/cron"

   The thread had only one message, and can be found via Google Groups here:

       https://groups.google.com/forum/#!topic/comp.os.linux/hPaY9XbDybE

   In this message Ed Carp announces his newly created at(1) and atrun(1)
   programs, along with a hint toward why he implemented them.


*** [1 of 1] comp.os.linux: 1992-08-11 08:25:49 GMT; Ed Carp; Subject: /bin/at, /usr/lib/atrun, & /etc/cron

    : Newsgroups: comp.os.linux
    : Path: sparky!uunet!unislc!erc
    : From: erc@unislc.uucp (Ed Carp)
    : Subject: /bin/at, /usr/lib/atrun, & /etc/cron
    : X-Newsreader: Tin 1.1 PL4
    : Message-ID: <1992Aug11.082549.12117@unislc.uucp>
    : Organization: Unisys Corporation SLC
    : Date: Tue, 11 Aug 1992 08:25:49 GMT
    : Lines: 16
    :
    : Taking a break from mailpak-1.3, I found I needed some periodic timer
    : execution stuff, and Paul Vixie's cron didn't quite fill the bill - I
    : needed something simpler ... something like the old /etc/cron that
    : ran stuff out of /usr/lib/crontab.  Oh, and while you're at it, Ed,
    : how about at and atrun, too?
    :
    : Well, folks, within the hour, it should be in tsx-11.mit.edu:/incoming/
    : periodic.tar.  No manpages, a simple README and install script, but
    : it works! :)
    :
    : Another quick hack from e...@apple.com :)
    : --
    : Ed Carp, N7EKG     e...@apple.com                801/538-0177
    : "This is the final task I will ever give you, and it  goes  on  forever.   Act
    : happy, feel happy, be happy, without a reason in the world. Then you can love,
    : and do what you will


** 1992-09-22: comp.os.linux thread (1 msg): "at.shar uploaded to tsx-11"

   The thread had only one message, and can be found via Google Groups here:

       https://groups.google.com/forum/#!topic/comp.os.linux/6B8mcM3e29E

   This is Ed Carp's at(1) program (bug fix release).


** 1992-12-22: comp.os.linux thread (9 posts): "Cron for Linux?"

   The thread had 9 posts, and can be found on Google Groups here:

       https://groups.google.com/forum/#!topic/comp.os.linux/jp4GEa795K4

   That thread is about cron(8) rather than at(1), but I mention it because Ed
   Carp is a participant and points out that there are two different cron
   implementations for Linux: his own, and the one from Paul Vixie.

   When Ed Carp first implemented his at(1) and atrun(1) programs, their
   distribution was bundled together with his collection of "periodic"
   programs, which also included his cron (see his 1992-08-11 post in
   comp.os.linux noted above). I'm pretty sure that I saw a post (don't have
   it handy at the moment) to this group -- a "software list for linux" type
   of post -- that listed Ed Carp's at-${version}.tgz (or something like that)
   as a separate artifact uploaded to sunsite. If I'm correct, that might mean
   that between August 1992 and December 1992 the two started to be
   distributed separately. Still digging.

   _UPDATE:_ I could find no further mention of at(1) on comp.os.linux until
   the 1993-07-21 thread (noted further down below) in which Ed Carp mentions
   that somebody had picked up working on the version he had distributed
   earlier.


** 1993-01-15: comp.os.linux.announce thread (1 msg): "at1-0.taz uploaded to tsx-11"

   The thread had only one message, and can be found via Google Groups here:

       https://groups.google.com/forum/#!topic/comp.os.linux.announce/pHKn4hIfL_A

   At the time of writing (2020-04-01), this is the earliest thread I've found
   (still looking) about a linux-specific at(1) implementation. There is
   subsequent activity on it, though, that I'll just document pointers to in
   case I need/want to dig deeper in that direction at some point:

   - 1993-01-19: "at-1.1.tar.Z uploaded to tsx-11.mit.edu"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/QwlDxZ1h_Z8

   - 1993-01-26: "at-1.1a.tar.Z uploaded to tsx-11"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/QwlDxZ1h_Z8

   - 1993-04-16: "at-1.2.tar.Z uploaded to tsx-11 and sunsite"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/iqmrsFp0h6g

   - 1993-09-30: "at-2.0 released"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/zNBEXAa7CmQ

     This message also notes, "David Parsons ... wrote the time parsing
     routines for 2.0; many thanks to him!".

   - 1993-10-03: "At 2.0 security bug; 2.1 uploaded to sunsite and tsx-11"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/-WJV7kHgI60

   - 1993-10-14: "at-2.2 uploaded to sunsite and tsx-11"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/8qIjFfo5kpo

   - 1993-10-17: "at-2.3 released"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/uk5plLTVLUA

   - 1993-11-20: "at 2.5 released"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/wihRNyVL5W8

   - 1994-03-01: "at-2.6 uploaded to tsx-11 and sunsite"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/nmLhNrlGij0

   - 1994-03-03: "at-2.6a uploaded to tsx-11 and sunsite"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/HHx2LV4V6p4

   - 1994-03-13: "at-2.6b uploaded"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/OIZGseYCNC0

   - 1994-05-10: "at-2.7 uploaded to tsx-11 and sunsite"

     https://groups.google.com/forum/#!topic/comp.os.linux.announce/IllX5qDq-ig

*** [1 of 1] comp.os.linux.announce: 1993-01-15 12:34:51 GMT; Thomas Koenig; Subject: at1-0.taz uploaded to tsx-11

    : Newsgroups: comp.os.linux.announce
    : Path: sparky!uunet!mcsun!news.funet.fi!hydra!klaava!wirzeniu
    : From: ig...@fg20.rz.uni-karlsruhe.de (Thomas Koenig)
    : Subject: at1-0.taz uploaded to tsx-11
    : Message-ID: <1993Jan15.123451.18126@klaava.Helsinki.FI>
    : Followup-To: comp.os.linux
    : Keywords: at, batch
    : Sender: wirz...@klaava.Helsinki.FI (Lars Wirzenius)
    : Organization: University of Karlsruhe, Germany
    : Date: Fri, 15 Jan 1993 12:34:51 GMT
    : Approved: linux-a...@tc.cornell.edu (Lars Wirzenius)
    : Lines: 15
    :
    : I have just uploaded at1-0.taz to tsx-11 and expect it to be in the
    : /pub/linux/sources/usr.bin directory fairly soon.
    :
    : It implements the at(1) and batch(1) commands, manpages are included.
    : People who have used the version of at(1) previously to be found at tsx-11
    : in a multi - user environment should update to this version, because of
    : a potential serious security hole in that version.
    :
    : Please send bug reports to ig...@rz.uni-karlsruhe.de.
    :
    : Happy hacking
    : --
    : Thomas Koenig, ig...@rz.uni-karlsruhe.de, ig25@dkauni2.bitnet
    : The joy of engineering is to find a straight line on a double logarithmic
    : diagram.


** 1993-07-20: comp.os.linux thread (1 msg): "at and atrun binaries - where to find them"

   The thread had only one message, and can be found via Google Groups here:

       https://groups.google.com/forum/#!topic/comp.os.linux/bZ-fLPH3tNM

*** [1 of 1] comp.os.linux: 1993-07-20 09:14:46 GMT; Nick Sandru; Subject: at and atrun binaries - where to find them

   : Path: gmd.de!xlink.net!howland.reston.ans.net!wupost!uunet!mcsun!dkuug!uts!cri.dk!csd!ns
   : Newsgroups: comp.os.linux
   : From: n...@csd.cri.dk (Nick Sandru)
   : Subject: at and atrun binaries - where to find them
   : Message-ID: <CAGHop.3I5@csd.cri.dk>
   : Followup-To: poster
   : Keywords: at atrun binaries
   : Sender: ne...@csd.cri.dk
   : Reply-To: n...@csd.cri.dk
   : Organization: Computer Resources International A/S, CASE div.
   : Date: Tue, 20 Jul 1993 09:14:46 GMT
   : Lines: 23
   :
   : I have just switched over to Linux (SLS distribution) and I need the binaries
   : for at and atrun. I looked into several FTP sites, but I found only the sources.
   : The problem is that I cannot install gcc etc. until I get a bigger disk (the
   : present one has only 44 Mbytes and cca 1/2 of it is occupied by a DOS partition),
   : so that I have no possiblity to compile the sources. The machine is an AT/386SX-40
   : with 4 Mbytes RAM. I have replaced its old 286 motherboard last week and I decided
   : to choose Linux as a replacement for the Minix OS I had used before.
   :
   : Otherwise the installation went without problems. I have replaced the smail package
   : from the distribution with sendmail-5.65+IDA last evening - it took only 30 minutes
   : to unpack and configure it...
   :
   : Thanks,
   :
   : Long Haired Nick
   :
   : ---
   : Nick Sandru - System administrator   | e-mail: n...@csd.cri.dk         (office)
   : Columbus Space Station SDE Project   |         n...@sandes.cri.dk      (home)
   : Computer Resources International A/S | phone:  +45 45 82 21 00 x2036 (office)
   : Bregnerodvej 144                     |         +45 47 98 06 27       (home)
   : DK-3460 Birkerod, Denmark            | fax:    +45 45 82 17 11


** 1993-07-21: comp.os.linux thread (2 msgs): "'at' under Linux ?"

   The thread had only two messages, and can be found via Google Groups here:

       https://groups.google.com/forum/#!topic/comp.os.linux/tM6DYgYQ81I

   The question was asked by Achim Bursian, and answered in the affirmative by
   Ed Carp.

*** [1 of 2] comp.os.linux: 1993-07-21 17:33:46 GMT; Achim Bursian; Subject: 'at' under Linux ?

    : Newsgroups: comp.os.linux
    : Path: gmd.de!Germany.EU.net!news.dfn.de!xlink.net!pilhuhn!flatlin!subnet.sub.net!hugis!skyjump!achim
    : From: ac...@skyjump.nbg.sub.org (Achim Bursian)
    : Subject: 'at' under Linux ?
    : Organization: ALLM (Achim's little Linux machine)
    : Date: Wed, 21 Jul 1993 17:33:46 GMT
    : Message-ID: <1993Jul21.173346.1548@skyjump.nbg.sub.org>
    : Lines: 9
    :
    : Is there no 'at' command under Linux (SLS1.02).
    : I can't find it.
    :
    : Thanks for help (please by mail)
    :      Achim
    : --
    : SNAIL-MAIL:   Achim Bursian  /  Loehestr.17  /  91054 Erlangen  /  Germany
    :     E-MAIL:   ac...@skyjump.nbg.sub.org
    :      VOICE:   (+49) 9131 57096                   Blue skies --- dive!


*** [2 of 2] comp.os.linux: 1993-07-22 1993 18:02:40 GMT; Ed Carp; Subject: Re: 'at' under Linux ?

    : Newsgroups: comp.os.linux
    : Path: gmd.de!newsserver.jvnc.net!yale.edu!spool.mu.edu!uwm.edu!cs.utexas.edu!uunet!olivea!sgigate!sgiblab!wetware!khijol!warrior!erc
    : From: erc@khijol.uucp (Ed Carp)
    : Subject: Re: 'at' under Linux ?
    : References: <1993Jul21.173346.1548@skyjump.nbg.sub.org>
    : Organization: The Center For World Control, Inc.
    : Date: Thu, 22 Jul 1993 18:02:40 GMT
    : X-Newsreader: TIN [version 1.1 PL8]
    : Message-ID: <CAKvGH.7xC@khijol.uucp>
    : Lines: 12
    :
    : Achim Bursian (ac...@skyjump.nbg.sub.org) wrote:
    :
    : : Is there no 'at' command under Linux (SLS1.02).
    : : I can't find it.
    :
    : Yes, there is.  I wrote one (along with atrun), someone posted a couple of
    : patches to it.  I think you can find it over on tsx-11.
    : --
    : Ed Carp				e...@apple.com			510/659-9560
    : "Disagreements are not meant to be challenges.  They are just a different
    :  reality."  -- Risa D'Angeles
    : DISCLAIMER:  I work for me ... what's it to you? :)


** 1993-08-11: comp.os.linux thread (10 msgs (only 3 relevant)): "[Q] Diffs from SysV specs?"

   This thread had 10 messages in August 1993, but only three of them are
   relevant to the history of the 'at' command in GNU/Linux:

       https://groups.google.com/forum/#!topic/comp.os.linux/xF3Rc0lZNQY

   A question was asked about a list of programs found Stephen R. Bourne's
   book "The UNIX System V Environment" that were not included in the SLS 1.03
   Linux distribution.

   The main useful response simply indicated that the 'at' and 'batch'
   commands are "Available on sunsite". I think that means the version of the
   'at' command written by Ed Carp, as mentioned above in his message from
   [1993-07-22 Thu].


*** [1 of 3] comp.os.linux: 1993-08-11 20:03:14 GMT; Petter Reinholdtsen; Subject: [Q] Diffs from SysV specs?

    : Newsgroups: comp.os.linux
    : Path: gmd.de!xlink.net!howland.reston.ans.net!agate!doc.ic.ac.uk!uknet!pipex!sunic!aun.uninett.no!news.uit.no!petterr
    : From: pet...@stud.cs.uit.no (Petter Reinholdtsen)
    : Subject: [Q] Diffs from SysV specs?
    : Summary: List of commands presumed missign in Linux.
    : Sender: ne...@news.uit.no (News admin.)
    : Message-ID: <1993Aug11.200314.21235@news.uit.no>
    : Date: Wed, 11 Aug 1993 20:03:14 GMT
    : Organization: University of Tromsoe, Norway
    : Keywords: Linux, SVID
    : Followup-To: comp.os.linux
    : Lines: 33
    :
    : Missing commands in SLS 1.02.
    : Mention by Stephen R. Bourne in "the UNIX System V enviroment"
    :
    : adb	- absolute debug
    : at,batch	- execure commands at a later time
    : cb	- C program beautifier
    : crypt	- encode/decode
    : deroff	- remove nroff, troff, tbl and eqn constructs
    : diction	- print wordly sentences; thesaurus for diction
    : eqn,neqn	- typeset mathematics
    : lint	- a C program checker
    : lorder	- find ordering relation for an object library
    : ptx	- permited index
    : sdb	- symbolic debugger
    : spell	- find spelling errors
    : style	- analyze surface characteristics of a document
    : tabs	- set tabs on a terminal
    : tbl	- format tables for nroff or troff
    : troff	- text formatting and typesetting
    : tsort	- topological sort
    : units	- conversion program
    :
    : Are this missing or unimplemented? Should this be links from
    : GNU-variants?
    :
    : ##>  Petter Reinholdtsen  <##
    :
    :
    : --
    : ##>  Petter Reinholdtsen <## | pet...@stud.cs.uit.no
    : Skolegata 7                  | Petter Reinholdtsen at 2:502/802.153
    : 9008 Tromsoe                 | University of Tromsoe, Norway


*** [2 of 3] comp.os.linux: 1993-08-12 01:24:39 GMT; Zack Evans; Subject: Re: [Q] Diffs from SysV specs?

    [I truncated this message after the relevant part]

    : Newsgroups: comp.os.linux
    : Path: gmd.de!xlink.net!howland.reston.ans.net!agate!doc.ic.ac.uk!uknet!pipex!uunet!mnemosyne.cs.du.edu!nyx!zevans
    : From: zev...@nyx.cs.du.edu (Zack Evans)
    : Subject: Re: [Q] Diffs from SysV specs?
    : Message-ID: <1993Aug12.012439.6256@mnemosyne.cs.du.edu>
    : Keywords: Linux, SVID
    : Sender: use...@mnemosyne.cs.du.edu (netnews admin account)
    : Organization: Nyx, The Spirit Of The Night @ U. of Denver Math/CS dept.
    : References: <1993Aug11.200314.21235@news.uit.no>
    : Date: Thu, 12 Aug 93 01:24:39 GMT
    : Lines: 72
    :
    : In article <1993Aug11....@news.uit.no>,
    : Petter Reinholdtsen <pet...@stud.cs.uit.no> wrote:
    : >Missing commands in SLS 1.02.
    : >Mention by Stephen R. Bourne in "the UNIX System V enviroment"
    :
    : >adb	- absolute debug
    :
    : A subset of gdb perhaps? Same goes for sdb.
    :
    : >at,batch	- execure commands at a later time
    :
    : Yeah cron is missing from MCC as well...no doubt its out there somewhere.

    [Message truncated]


*** [3 of 3] comp.os.linux: 1993-08-12 13:11:38 GMT; Nick Hilliard; Subject: Re: [Q] Diffs from SysV specs?

    [I truncated this message after the relevant part]

    : Newsgroups: comp.os.linux
    : Path: gmd.de!xlink.net!howland.reston.ans.net!europa.eng.gtefsd.com!uunet!mcsun!ieunet!ieunet!quay.ie!nick
    : From: ni...@quay.ie (Nick Hilliard)
    : Subject: Re: [Q] Diffs from SysV specs?
    : Message-ID: <Aug12.131138.20954@quay.ie>
    : Date: Thu, 12 Aug 1993 13:11:38 GMT
    : References: <1993Aug11.200314.21235@news.uit.no>
    : Organization: Quay Financial Software
    : X-Newsreader: TIN [version 1.2 PL0]
    : Lines: 57
    :
    : Petter Reinholdtsen (pet...@stud.cs.uit.no) wrote:
    : : Missing commands in SLS 1.02.
    : : Mention by Stephen R. Bourne in "the UNIX System V enviroment"
    :
    : : adb	- absolute debug
    :
    : See gdb?
    :
    : : at,batch	- execure commands at a later time
    :
    : Available on sunsite.

    [Message truncated]


** 1993-08-23: comp.os.linux thread (1 msg): "crontab or at?"

   A thread with a single (zero-content) message:

       https://groups.google.com/forum/#!topic/comp.os.linux/5FZQoyyjdL4

   I'm including this one in my notes here mainly for completeness, with the
   excuse that the question suggests that the answer was not "just known by
   everybody" at the time the question (in the subject line) was asked.

*** [1 of 1] comp.os.linux: 1993-08-23 08:50:55 GMT; Sylphid C. Su; Subject: crontab or at?

    : Newsgroups: comp.os.linux
    : Path: gmd.de!xlink.net!sol.ctr.columbia.edu!howland.reston.ans.net!newsserver.jvnc.net!news.edu.tw!news!sparc4.ncu.edu.tw!halley!sylphid
    : From: syl...@phy.ncu.edu.tw (Sylphid C. Su)
    : Subject: crontab or at?
    : Message-ID: <1993Aug23.085055.1025@sparc4.ncu.edu.tw>
    : Sender: ne...@sparc4.ncu.edu.tw
    : Organization: Computer Center Of NCU in R.O.C.
    : X-Newsreader: TIN [version 1.2 PL1]
    : Date: Mon, 23 Aug 1993 08:50:55 GMT
    : Lines: 1



** 1993-10-17: comp.os.linux.misc thread (1 msg):

   This thread had a one-shot announcement about the release of at-2.3:

       https://groups.google.com/forum/#!topic/comp.os.linux.misc/uk5plLTVLUA

   This documents that Koenig's work on it had been well underway before the
   middle of October 1993.

*** [1 of 1] comp.os.linux.misc: 1993-10-17 15:04:38 GMT; Thomas Koenig; Subject: at-2.3 released

    : Xref: gmd.de comp.os.linux.announce:1302 comp.os.linux.misc:2968
    : Path: gmd.de!newsserver.jvnc.net!howland.reston.ans.net!usc!elroy.jpl.nasa.gov!decwrl!concert!samba.oit.unc.edu!bounce-bounce
    : From: ig...@fg70.rz.uni-karlsruhe.de (Thomas Koenig)
    : Newsgroups: comp.os.linux.announce,comp.os.linux.misc
    : Subject: at-2.3 released
    : Followup-To: comp.os.linux.misc,comp.os.linux.misc
    : Date: 17 Oct 1993 15:04:38 GMT
    : Organization: University of Karlsruhe, Germany
    : Lines: 40
    : Approved: linux-a...@tc.cornell.edu (Matt Welsh)
    : Message-ID: <29rmu6$7hf@samba.oit.unc.edu>
    : Reply-To: ig...@fg70.rz.uni-karlsruhe.de (Thomas Koenig)
    : NNTP-Posting-Host: calypso.oit.unc.edu
    : Keywords: at, cron, daemon, scheduling, crond
    : Originator: mdw@sunSITE
    :
    : Hello, world;
    :
    : I've just uploaded at 2.3 to sunsite.unc.edu and tsx-11.mit.edu.
    : It's Yet Another Bugfix release; this time, it fixes the -f option which
    : was broken in 2.2, and also makes sure that environment variables are
    : actually exported.
    :
    : Again, here's the lsm entry:
    :
    : Begin2
    : Title        = at
    : Version      = at-2.3
    : Desc1        = At is an implementation of at(1) for running commands at
    : Desc2        = a specified time.  It now features times such as
    : Desc3        = at now + 10 minutes or at tomorrow 3:00 pm.
    : Author       = Thomas Koenig
    : AuthorEmail  = ig...@rz.uni-karlsruhe.de
    : Maintainer   = Thomas Koenig
    : MaintEmail   = ig...@rz.uni-karlsruhe.de
    : Site1        = tsx-11.mit.edu
    : Path1        = /pub/linux/sources/usr.bin/
    : File1        = at-2.3.tgz
    : FileSize1    = 22856
    : Site2        = sunsite.unc.edu
    : Path2        = /pub/Linux/system/Daemons
    : File2        = at-2.3.tgz
    : FileSize2    = 22856
    : Required1    = crond
    : CopyPolicy1  = GNU Copyleft
    : Comment1     = David Parsons (o...@pell.chi.il.us) wrote the time parsing
    : Comment2     = routines for 2.0; many thanks to him!
    : Entered      = 16OCT93
    : EnteredBy    = Thomas Koenig
    : End
    :
    : --
    : Thomas Kvnig, ig...@rz.uni-karlsruhe.de, ig25@dkauni2.bitnet
    : The joy of engineering is to find a straight line on a double
    : logarithmic diagram.


* Questions for Thomas König (Thomas Koenig)

  Q: Is there anybody maintaining a version of 'at' (and friends) currently
     that you would consider to be the authoritative source of your original
     code?

  Q: What was your original motivation for for writing at(1)?

     a. Was it ever considered to simply use the at(1) command from the Net/2
        BSD Distribution? If that idea was considered and rejected, why?
        (Technical reasons?  Legal/licensing reasons? Something else?)

     b. Is there any relationship between your at(1) command and the at(1)
        command that Ed Carp mentions that he wrote on comp.lang.linux on
        1993-07-22? Were they entirely different implementations?

  Q: How did your at(1) program come to be the one used in all of the mainline
     BSD's in 1993?

     While 4.4BSD-Lite kept the 'at.c' from the earlier 4.3BSD-Reno and Net/2
     distributions, 386BSD, NetBSD, and FreeBSD all used your version.


* New at(1) feature: support TIME_STYLE env var, --time-style=TIME_STYLE opt

  This would work similarly to the support for the TIME_STYLE environment
  variable that exists in GNU ls(1) and GNU du(1), and could eliminate the
  need for atat(1) or similar.

** debian bug #612075: "atq date format is not easily sortable"

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=612075

   This is a wishlist bug filed in 2011-02 by Bernard Hatt
   <bmh@arkady.demon.co.uk> asking for a command line option to have the
   atq(1) output sorted (or to at least have the default output emit the jobs
   listing "in execution time order".

   This isn't quite what I have in mind, but it scratches the same itch that
   motivated me to write atat(1). I think if such a feature is going to be
   "officially supported", then it should behave consisently with GNU ls(1)
   and GNU du(1), to the extent that it makes sense. That means the command
   line option should be '--time-style=TIME_STYLE', and the values it accepts
   match those accepted by those other progs.

   A patch was attached in 2014-07 by Petr Gajdos <pgajdos@suse.cz>, which
   adds a '-o timeformat' option to atq(1) that accepts a value that can be
   used as the format argument to strftime(3).

   The issue is tagged as:

   :    Tags: confirmed, patch, upstream

   What does 'upstream' mean in this case? AFAICT, Debian is its own
   "upstream" in this case; it seems that the package maintainer and the
   upstream source are one and the same: Jose M Calhariz <calhariz@debian.org>

   The 'at' package metadata lists Calhariz's site as the project's homepage:

       http://blog.calhariz.com

*** TODO: Confirm whether or not I have that right (Calhariz both packager and upstream for 'at'?)
